[package]
name = "neli"
version = "0.4.3"
authors = ["John Baublitz <john.m.baublitz@gmail.com>"]
description = "Type safe netlink library written in Rust"
license = "BSD-3-Clause"
repository = "https://github.com/jbaublitz/neli"
keywords = ["netlink"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "LICENSE",
]

[lib]
name = "neli"
path = "src/lib.rs"

[dependencies]
byteorder = "1.2"
libc = "0.2.66"

[dependencies.tokio]
version = "0.2.0-alpha.6"
optional = true

[dependencies.tokio-net]
version = "0.2.0-alpha.6"
optional = true

[dependencies.mio]
version = "0.6"
optional = true

[dependencies.buffering]
version = "0.4"
features = ["copy"]

[features]
default = []
stream = ["tokio", "mio", "tokio-net"]
