[package]
name = "neli"
version = "0.4.3"
authors = ["John Baublitz <john.m.baublitz@gmail.com>"]
description = "Type safe netlink library written in Rust"
license = "BSD-3-Clause"
repository = "https://github.com/jbaublitz/neli"
keywords = ["netlink"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "LICENSE",
]

[lib]
name = "neli"
path = "src/lib.rs"

[dependencies]
byteorder = "1.2"
libc = "0.2.66"

[dependencies.tokio]
git = "https://github.com/tokio-rs/tokio.git"
features = ["io-driver"]
optional = true

[dependencies.mio]
version = "0.6.20"
optional = true

[dependencies.futures-core]
version = "0.3.0"
optional = true

[dependencies.futures-sink]
version = "0.3.0"
optional = true

[dependencies.futures-util]
version = "0.3.0"
default-features = false
optional = true

[dependencies.pin-project-lite]
version = "0.1"
optional = true

[dependencies.buffering]
version = "0.4"
features = ["copy"]

[features]
default = []
stream = ["tokio", "mio","futures-core","futures-sink","pin-project-lite","futures-util"]
